[package]
name = "rust_json_webtoken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "=9.3.0"
serde = { version = "1.0.202", features = ["derive"] }
